const User = require("../models/User");
const { faker } = require("@faker-js/faker");

const ethiopianMaleNames = [
  "Abebe Bekele",
  "Adamu Tesfaye",
  "Assefa Gebremedhin",
  "Biniam Alemu",
  "Dawit Wolde",
  "Fikru Haile",
  "Gebre Yohannes",
  "Haile Selassie",
  "Kebede Tadesse",
  "Melaku Worku",
  "Abera Alemayehu",
  "Biruk Eshetu",
  "Dagne Teshome",
  "Efrem Kassa",
  "Fikadu Tilahun",
  "Getachew Desta",
  "Hailemariam Tsegaye",
  "Kassahun Mengistu",
  "Lemlem Abebe",
  "Meles Zenawi",
  "Negash Tadesse",
  "Samson Alemu",
  "Tariku Girma",
  "Yonas Tesfaye",
  "Zelalem Mulugeta",
  "Alemayehu Worku",
  "Bereket Gebre",
  "Dagnachew Belete",
  "Elias Kassahun",
  "Fikre Assefa",
  "Getnet Abera",
  "Haile Gebre",
  "Kassa Mekonnen",
  "Lelisa Desalegn",
  "Mekonnen Tesfaye",
  "Nega Alemu",
  "Selamawit Yohannes",
  "Tesfaye Gebremedhin",
  "Worku Kebede",
  "Yared Belay",
  "Zewdu Bekele",
  "Abraham Tadesse",
  "Bethelhem Melaku",
  "Dereje Birhanu",
  "Ermias Haile",
  "Fitsum Mekonnen",
  "Girma Teshome",
  "Hailu Fekadu",
  "Kebede Mekuria",
  "Lema Zenawi",
  "Merhawi Tsegaye",
  "Negasi Alemu",
  "Selassie Tadesse",
  "Tewodros Yonas",
  "Yohannes Haile",
  "Zerihun Asfaw",
  "Abel Tsegaye",
  "Belete Berhanu",
  "Demeke Alemayehu",
  "Endale Assefa",
  "Fekadu Mekonnen",
  "Gashaw Alemu",
  "Hagos Mekuria",
  "Kidanemariam Abebe",
  "Lulit Tesfaye",
  "Mesfin Getachew",
  "Netsanet Haile",
  "Sisay Wolde",
  "Tilahun Mekuria",
  "Yisak Gebre",
  "Zemariam Abebe",
  "Aklilu Haile",
  "Beza Yohannes",
  "Desta Gebre",
  "Ezra Alemayehu",
  "Fikremariam Mekuria",
  "Girma Haile",
  "Haileab Tadesse",
  "Kidane Alemayehu",
  "Luel Yilma",
  "Mulugeta Mekonnen",
  "Nigusu Assefa",
  "Semere Tadesse",
  "Tesfom Haile",
  "Wondimu Alemu",
  "Yoseph Tadesse",
  "Zerihun Tesfaye",
  "Amha Haile",
  "Birhanu Tadesse",
  "Dagnachew Assefa",
  // Add more names as needed
];

const ethiopianFemaleNames = [
  "Aster Mulugeta",
  "Desta Yirga",
  "Hirut Assefa",
  "Lemlem Hailu",
  "Mulu Demissie",
  "Seble Gebru",
  "Tigist Alemayehu",
  "Woini Kebede",
  "Yodit Tsegaye",
  "Zewditu Mengistu",
  "Abeba Tesfaye",
  "Betelhem Melaku",
  "Chaltu Admasu",
  "Dinknesh Eshetu",
  "Eleni Abebe",
  "Fikirte Alemayehu",
  "Genet Abebe",
  "Haimanot Tadesse",
  "Kidist Alemu",
  "Lulit Yonas",
  "Marta Gebre",
  "Nardos Alemayehu",
  "Rahel Teshome",
  "Selamawit Gebremedhin",
  "Tizita Assefa",
  "Wubit Kebede",
  "Yetnayet Tesfaye",
  "Zena Tadesse",
  "Aberash Mengistu",
  "Biruktawit Gebre",
  "Dagmawit Alemu",
  "Eyerusalem Assefa",
  "Fana Alemayehu",
  "Gebeyanesh Haile",
  "Hanna Gebre",
  "Kalkidan Tesfaye",
  "Liya Mulugeta",
  "Meklit Alemayehu",
  "Netsanet Haile",
  "Rediet Yonas",
  "Sara Gebremedhin",
  "Senait Alemu",
  "Tena Yonas",
  "Worknesh Haile",
  "Yeshi Tadesse",
  "Zemenay Eshetu",
  "Adanech Tesfaye",
  "Berhane Alemu",
  "Debritu Yonas",
  "Emebet Haile",
  "Fikir Assefa",
  "Genet Tesfaye",
  "Hirut Gebremedhin",
  "Kelemua Alemayehu",
  "Liyu Haile",
  "Mulu Gebremedhin",
  "Nigist Assefa",
  "Ruth Tadesse",
  "Shewaye Alemayehu",
  "Tsehay Yonas",
  "Wubit Abebe",
  "Yalem Tadesse",
  "Zerfeshiwal Eshetu",
  "Alemnesh Tesfaye",
  "Banchi Alemayehu",
  "Dawit Yonas",
  "Elshaday Tesfaye",
  "Freweyni Gebremedhin",
  "Gennet Yonas",
  "Hanna Abebe",
  "Kebebush Haile",
  "Lensa Gebremedhin",
  "Martha Tesfaye",
  "Nunu Alemayehu",
  "Segen Tadesse",
  "Tadese Alemayehu",
  "Wudnesh Haile",
  "Yeharerwerk Yonas",
  "Zenebech Alemayehu",
  "Ayalew Tesfaye",
  "Bizunesh Alemayehu",
  "Dawit Gebremedhin",
  "Eyerusalem Tadesse",
  "Fikre Haile",
  "Genene Tesfaye",
  "Hana Yonas",
  "Konjit Alemayehu",
  "Lensa Tadesse",
  "Meron Abebe",
  "Netsanet Tadesse",
  "Selam Gebremedhin",
  "Teshale Alemayehu",
  "Yeshi Haile",
  "Zena Tadesse",
  // Add more names as needed
];

const ethinicGroups = [
  "Oromo",
  "Amhara",
  "Tigray",
  "Somali",
  "Sidama",
  "Gurage",
  "Welayta",
  "Hadiya",
  "Afar",
  "Gamo",
  "Beta Israel (Falasha)",
  //   "Nuer",
  //   "Anuak",
  //   "Mursi",
  //   "Harari",
  //   "Konso",
  //   "Kafficho",
];

const languages = [
  "Amharic",
  "Oromo",
  "Tigrinya",
  "Somali",
  "Afar",
  "Sidama",
  "Wolayta",
  "Gurage",
  "Hadiya",
  "Tigre",
  "Kambaata",
  "Harari",
  "Afaan Orma",
  "Silte",
  "Bench",
  "Dawro",
  "Konso",
  "English",
  "Spanish",
  "Chinese",
  "French",
  "Arabic",
  "Russian",
  "Portuguese",
  "German",
  "Japanese",
  "Korean",
];

// const ethnicGroups = [
//   "Afar",
//   "Amhara",
//   "Argobba",
//   "Agew",
//   "Ari",
//   "Berta",
//   "Borana",
//   "Buno",
//   "Chepang",
//   "Chaha",
//   "Daasanach",
//   "Dawro",
//   "Erob",
//   "Gamo",
//   "Gedeo",
//   "Gurage",
//   "Hadiya",
//   "Hamar",
//   "Harari",
//   "Irob",
//   "Jijiga",
//   "Kambaata",
//   "Kafa",
//   "Kannib",
//   "Kefa",
//   "Kola",
//   "Konso",
//   "Kushite",
//   "Maji",
//   "Mao",
//   "Mursi",
//   "Nuer",
//   "Oromo",
//   "Saho",
//   "Sidama",
//   "Silt'e",
//   "Somali",
//   "Suri",
//   "Tigray",
//   "Tigrinya",
//   "Wolaita",
//   "Woreda",
//   "Zay",
//   "Amharic",
//   "Anuak",
//   "Arbore",
//   "Berta",
//   "Blish",
//   "Brahmin",
//   "Cushitic",
//   "Dizi",
//   "Goffa",
//   "Gurage",
//   "Gamo",
//   "Gedeo",
//   "Gurage",
//   "Kambo",
//   "Konso",
//   "Kaficho",
//   "Kembata",
//   "Maji",
//   "Maale",
//   "Mursi",
//   "Nuer",
//   "Omotic",
//   "Shakacho",
//   "Sido",
//   "Shere",
//   "Tama",
//   "Tsemay",
//   "Welayta",
//   "Xer",
//   "Zergi",
//   "Zime",
//   "Banna",
//   "Benishangul",
//   "Berta",
//   "Gurage",
//   "Kachin",
//   "Kambata",
//   "Koore",
//   "Malla",
// ];

const createMockUser = (gender) => {
  const name =
    gender === "Male"
      ? ethiopianMaleNames[
          Math.floor(Math.random() * ethiopianMaleNames.length)
        ]
      : ethiopianFemaleNames[
          Math.floor(Math.random() * ethiopianFemaleNames.length)
        ];

  return {
    phoneNumber: `+2519${faker.number.int({ min: 10000000, max: 99999999 })}`,
    isVerified: true,
    profile: {
      personalInformation: {
        fullname: name,
        gender: gender,
        dateOfBirth: faker.date.past({
          years: 30,
          refDate: new Date(2000, 0, 1),
        }),
        location: "Ethiopia",
        occupation: faker.person.jobType(),
        educationalLevel: faker.helpers.arrayElement([
          "High School",
          "Diploma",
          "Bachelors",
          "Masters",
          "PhD",
        ]),
        ethnicity: faker.helpers.arrayElement(ethinicGroups),
        religion: faker.helpers.arrayElement([
          "Orthodox Christianity",
          "Muslim",
          "Protestant Christianity",
          "Catholicism",
          "Other",
        ]),
        languagesSpoken: faker.helpers.arrayElement(languages),
      },
      physicalAttributes: {
        height: faker.number.int({ min: 150, max: 200 }),
        weight: faker.number.int({ min: 50, max: 100 }),
        bodyType: faker.helpers.arrayElement([
          "Slim",
          "Average",
          "Athletic",
          "Heavy",
        ]),
      },
      lifestyle: {
        smoking: faker.helpers.arrayElement(["Yes", "No"]),
        drinking: faker.helpers.arrayElement(["Yes", "No"]),
        exercise: faker.helpers.arrayElement([
          "Regularly",
          "Occasionally",
          "Rarely",
        ]),
        diet: faker.helpers.arrayElement(["Vegetarian", "Non-Vegetarian"]),
      },
      interests: {
        favoriteSports: faker.helpers.arrayElements([
          "Soccer",
          "Basketball",
          "Running",
          "Swimming",
        ]),
        hobbies: faker.helpers.arrayElements([
          "Reading",
          "Traveling",
          "Music",
          "Cooking",
        ]),
        musicGenres: faker.helpers.arrayElements([
          "Pop",
          "Jazz",
          "Rock",
          "Classical",
        ]),
        travelPreferences: faker.helpers.arrayElements([
          "Beach",
          "Mountains",
          "City",
        ]),
        culturalInterests: faker.helpers.arrayElements([
          "Art",
          "History",
          "Literature",
        ]),
        communicationStyles: faker.helpers.arrayElements([
          "Direct",
          "Indirect",
        ]),
        relationshipGoals: faker.helpers.arrayElements([
          "Long-term",
          "Short-term",
        ]),
      },
    },
  };
};

exports.seedData = async (req, res) => {
  const maleUsers = Array.from({ length: 4 }, () => createMockUser("Male"));
  const femaleUsers = Array.from({ length: 4 }, () => createMockUser("Female"));

  try {
    await User.insertMany([...maleUsers, ...femaleUsers]);
    res.status(200).send({ message: "Seed data created successfully" });
  } catch (error) {
    res.status(500).send({ message: "Error seeding data", error });
  }
};
